# Use a base image that includes the Python SDK for Apache Beam
FROM apache/beam_python3.9_sdk:2.67.0

# Set the working directory
WORKDIR /app

# Copy your entire dataflow package and setup.py
COPY . /app/dataflow
COPY setup.py /app/dataflow/

# Install your package and its dependencies
RUN pip install --no-cache-dir /app/dataflow